# Tests for vlen-utf8 string encoding. The ground-truth fixture below
# was generated by Python's numcodecs.VLenUTF8 (the canonical encoder
# used by zarr-python). It pins the wire format byte-for-byte;
# round-trip tests verify encoder + decoder self-consistency for the
# cases the fixture doesn't cover.

# === GROUND-TRUTH FIXTURE ===
# Generated 2026-04-29 by:
#   python3 -c 'import numcodecs, numpy
#               codec = numcodecs.VLenUTF8()
#               arr = numpy.array(["A","B","C"], dtype=object)
#               print(" ".join(f"{b:02x}" for b in codec.encode(arr)))'
# Output: 03 00 00 00 01 00 00 00 41 01 00 00 00 42 01 00 00 00 43
.UPSTREAM_VLEN_UTF8_BYTES_ABC <- as.raw(c(
    # 4 bytes: N=3 (little-endian uint32)
    0x03, 0x00, 0x00, 0x00,
    # 4 bytes: len("A")=1
    0x01, 0x00, 0x00, 0x00,
    # 1 byte: "A"
    0x41,
    # 4 bytes: len("B")=1
    0x01, 0x00, 0x00, 0x00,
    # 1 byte: "B"
    0x42,
    # 4 bytes: len("C")=1
    0x01, 0x00, 0x00, 0x00,
    # 1 byte: "C"
    0x43
))

# Pinned: should be 19 bytes total (4 + 3*(4+1)).

test_that("vlen-utf8 encoder produces upstream-compatible bytes for ABC", {
    bytes <- dafr:::zarr_v2_encode_strings(c("A", "B", "C"))
    expect_identical(bytes, .UPSTREAM_VLEN_UTF8_BYTES_ABC)
})

test_that("vlen-utf8 decoder reads upstream-emitted bytes for ABC", {
    decoded <- dafr:::zarr_v2_decode_strings(.UPSTREAM_VLEN_UTF8_BYTES_ABC,
                                              n = 3L)
    expect_identical(decoded, c("A", "B", "C"))
})

test_that("vlen-utf8 round-trips empty input", {
    bytes <- dafr:::zarr_v2_encode_strings(character(0L))
    expect_length(bytes, 4L)  # just the N=0 header
    decoded <- dafr:::zarr_v2_decode_strings(bytes)
    expect_identical(decoded, character(0L))
})

test_that("vlen-utf8 round-trips empty strings", {
    bytes <- dafr:::zarr_v2_encode_strings(c("", "", ""))
    decoded <- dafr:::zarr_v2_decode_strings(bytes, n = 3L)
    expect_identical(decoded, c("", "", ""))
})

test_that("vlen-utf8 round-trips multi-byte UTF-8", {
    inputs <- c("hello", "α β γ", "日本語", "\U0001f680")
    bytes <- dafr:::zarr_v2_encode_strings(inputs)
    decoded <- dafr:::zarr_v2_decode_strings(bytes, n = length(inputs))
    expect_identical(decoded, inputs)
})

test_that("vlen-utf8 round-trips a long single string", {
    long <- paste(rep("x", 10000L), collapse = "")
    bytes <- dafr:::zarr_v2_encode_strings(long)
    decoded <- dafr:::zarr_v2_decode_strings(bytes)
    expect_identical(decoded, long)
})

test_that("vlen-utf8 round-trips a many-string array", {
    inputs <- sprintf("entry_%d", seq_len(1000L))
    bytes <- dafr:::zarr_v2_encode_strings(inputs)
    decoded <- dafr:::zarr_v2_decode_strings(bytes, n = length(inputs))
    expect_identical(decoded, inputs)
})

test_that("vlen-utf8 encoder rejects NA strings", {
    expect_error(dafr:::zarr_v2_encode_strings(c("a", NA_character_, "b")),
                 "NA strings not supported")
})

test_that("vlen-utf8 encoder rejects non-character input", {
    expect_error(dafr:::zarr_v2_encode_strings(c(1L, 2L)),
                 "must be a character")
})

test_that("vlen-utf8 decoder rejects truncated header", {
    expect_error(dafr:::zarr_v2_decode_strings(raw(2L)),
                 "truncated|count header")
})

test_that("vlen-utf8 decoder rejects truncated payload", {
    # Header says 1 string of length 5, but only 2 bytes follow.
    bad <- as.raw(c(0x01, 0x00, 0x00, 0x00,    # N = 1
                    0x05, 0x00, 0x00, 0x00,    # len = 5
                    0x41, 0x42))               # only 2 bytes (truncated)
    expect_error(dafr:::zarr_v2_decode_strings(bad),
                 "truncated")
})

test_that("vlen-utf8 decoder rejects mismatched n", {
    bytes <- dafr:::zarr_v2_encode_strings(c("A", "B"))
    expect_error(dafr:::zarr_v2_decode_strings(bytes, n = 3L),
                 "differs from expected")
})

test_that("vlen-utf8 returned strings are marked UTF-8 encoded", {
    bytes <- dafr:::zarr_v2_encode_strings("日本語")
    decoded <- dafr:::zarr_v2_decode_strings(bytes)
    expect_identical(Encoding(decoded), "UTF-8")
})
