test_that("files_daf format_replace_reorder rewrites vector + matrix payloads", {
    tmp <- tempfile()
    d_mem <- memory_daf()
    add_axis(d_mem, "cell", c("A", "B", "C"))
    add_axis(d_mem, "gene", c("X", "Y"))
    set_vector(d_mem, "cell", "x", c(10, 20, 30))
    set_matrix(d_mem, "cell", "gene", "M", matrix(1:6, nrow = 3))
    fd_w <- files_daf(tmp, mode = "w")
    copy_all(fd_w, d_mem, relayout = FALSE)
    plan <- dafr:::.build_reorder_plan(fd_w, list(cell = c(2L, 3L, 1L)))
    dafr:::format_replace_reorder(fd_w, plan)
    dafr:::format_cleanup_reorder(fd_w, plan)
    rm(fd_w)
    fd_r <- files_daf(tmp, mode = "r")
    expect_identical(axis_vector(fd_r, "cell"), c("B", "C", "A"))
    expect_equal(unname(get_vector(fd_r, "cell", "x")), c(20, 30, 10))
    m <- get_matrix(fd_r, "cell", "gene", "M")
    expect_equal(unname(m[, 1]), c(2, 3, 1))
})

test_that("files_daf reorder leaves no .reorder.backup/ behind on success", {
    tmp <- tempfile()
    d_mem <- memory_daf()
    add_axis(d_mem, "cell", c("A", "B"))
    set_vector(d_mem, "cell", "x", c(1, 2))
    fd_w <- files_daf(tmp, mode = "w")
    copy_all(fd_w, d_mem, relayout = FALSE)
    plan <- dafr:::.build_reorder_plan(fd_w, list(cell = c(2L, 1L)))
    dafr:::format_replace_reorder(fd_w, plan)
    dafr:::format_cleanup_reorder(fd_w, plan)
    expect_false(dir.exists(file.path(tmp, ".reorder.backup")))
})

test_that("files_daf reorder bumps version counters on success", {
    tmp <- tempfile()
    d_mem <- memory_daf()
    add_axis(d_mem, "cell", c("A", "B"))
    set_vector(d_mem, "cell", "x", c(1, 2))
    fd_w <- files_daf(tmp, mode = "w")
    copy_all(fd_w, d_mem, relayout = FALSE)
    a0 <- axis_version_counter(fd_w, "cell")
    v0 <- vector_version_counter(fd_w, "cell", "x")
    plan <- dafr:::.build_reorder_plan(fd_w, list(cell = c(2L, 1L)))
    dafr:::format_replace_reorder(fd_w, plan)
    dafr:::format_cleanup_reorder(fd_w, plan)
    expect_gt(axis_version_counter(fd_w, "cell"), a0)
    expect_gt(vector_version_counter(fd_w, "cell", "x"), v0)
})

test_that("files_daf reorder preserves dimnames on read after reopen", {
    tmp <- tempfile()
    d_mem <- memory_daf()
    add_axis(d_mem, "cell", c("A", "B", "C"))
    add_axis(d_mem, "gene", c("X", "Y"))
    set_matrix(d_mem, "cell", "gene", "M", matrix(1:6, nrow = 3))
    fd_w <- files_daf(tmp, mode = "w")
    copy_all(fd_w, d_mem, relayout = FALSE)
    plan <- dafr:::.build_reorder_plan(fd_w, list(cell = c(2L, 3L, 1L)))
    dafr:::format_replace_reorder(fd_w, plan)
    dafr:::format_cleanup_reorder(fd_w, plan)
    rm(fd_w)
    fd_r <- files_daf(tmp, mode = "r")
    m <- get_matrix(fd_r, "cell", "gene", "M")
    expect_identical(rownames(m), c("B", "C", "A"))
    expect_identical(colnames(m), c("X", "Y"))
})

test_that("files_daf reorder handles sparse matrix correctly", {
    tmp <- tempfile()
    d_mem <- memory_daf()
    add_axis(d_mem, "cell", c("A", "B", "C"))
    add_axis(d_mem, "gene", c("X", "Y"))
    sp <- Matrix::sparseMatrix(i = c(1L, 2L, 3L), j = c(1L, 2L, 1L),
                               x = c(1.0, 2.0, 3.0), dims = c(3L, 2L))
    set_matrix(d_mem, "cell", "gene", "S", sp)
    fd_w <- files_daf(tmp, mode = "w")
    copy_all(fd_w, d_mem, relayout = FALSE)
    plan <- dafr:::.build_reorder_plan(fd_w, list(cell = c(3L, 1L, 2L)))
    dafr:::format_replace_reorder(fd_w, plan)
    dafr:::format_cleanup_reorder(fd_w, plan)
    rm(fd_w)
    fd_r <- files_daf(tmp, mode = "r")
    m <- get_matrix(fd_r, "cell", "gene", "S")
    expect_equal(as.numeric(m[1, ]), c(3.0, 0.0))
    expect_equal(as.numeric(m[2, ]), c(1.0, 0.0))
    expect_equal(as.numeric(m[3, ]), c(0.0, 2.0))
})

test_that("files_daf format_reset_reorder is no-op when no .reorder.backup/ exists", {
    tmp <- tempfile()
    d_mem <- memory_daf()
    add_axis(d_mem, "cell", c("A", "B"))
    fd_w <- files_daf(tmp, mode = "w")
    copy_all(fd_w, d_mem, relayout = FALSE)
    expect_silent(dafr:::format_reset_reorder(fd_w))
})

# ---- Public API ------------------------------------------------------------

test_that("reorder_axes() works end-to-end on files_daf with reopen", {
    tmp <- tempfile()
    d_mem <- memory_daf()
    add_axis(d_mem, "cell", c("A", "B", "C"))
    add_axis(d_mem, "gene", c("X", "Y"))
    set_vector(d_mem, "cell", "x", c(10, 20, 30))
    set_matrix(d_mem, "cell", "gene", "M", matrix(1:6, nrow = 3))
    fd_w <- files_daf(tmp, mode = "w")
    copy_all(fd_w, d_mem, relayout = FALSE)
    reorder_axes(fd_w, cell = c(2L, 3L, 1L))
    rm(fd_w)
    fd_r <- files_daf(tmp, mode = "r")
    expect_identical(axis_vector(fd_r, "cell"), c("B", "C", "A"))
    expect_equal(unname(get_vector(fd_r, "cell", "x")), c(20, 30, 10))
    m <- get_matrix(fd_r, "cell", "gene", "M")
    expect_equal(unname(m[, 1]), c(2, 3, 1))
})

test_that("reset_reorder_axes() on a clean files_daf is a no-op", {
    tmp <- tempfile()
    d_mem <- memory_daf()
    add_axis(d_mem, "cell", c("A"))
    fd_w <- files_daf(tmp, mode = "w")
    copy_all(fd_w, d_mem, relayout = FALSE)
    expect_silent(reset_reorder_axes(fd_w))
})
