test_that(".metadata_json_rebuild matches Julia's metadata.json structure", {
    root <- withr::local_tempdir()
    d <- files_daf(root, mode = "w+", name = "m")
    add_axis(d, "cell", paste0("c", 1:5)); add_axis(d, "gene", paste0("g", 1:3))
    set_scalar(d, "title", "hello"); set_scalar(d, "k", 7L)
    set_vector(d, "cell", "score", as.numeric(1:5))
    set_matrix(d, "cell", "gene", "dense", matrix(as.numeric(1:15), 5, 3))
    dafr:::.metadata_json_rebuild(root)
    m <- jsonlite::fromJSON(file.path(root, "metadata.json"), simplifyVector = FALSE)
    expect_equal(m[["axes/cell"]], list(format = "axis", n_entries = 5L))
    expect_equal(m[["scalars/title"]], list(type = "String", value = "hello"))
    expect_equal(m[["scalars/k"]], list(type = "Int32", value = 7L))
    expect_equal(m[["vectors/cell/score"]], list(format = "dense", eltype = "Float64"))
    expect_equal(m[["matrices/cell/gene/dense"]], list(format = "dense", eltype = "Float64"))
})
