test_that("tbl() on a Daf returns a daf_axis_tbl for the named axis", {
    skip_if_not_installed("dplyr")
    skip_if_not_installed("tibble")
    d <- memory_daf()
    add_axis(d, "cell", c("c1", "c2", "c3"))
    set_vector(d, "cell", "donor", c("A", "B", "A"))
    x <- dplyr::tbl(d, "cell")
    expect_s3_class(x, "daf_axis_tbl")
    expect_identical(attr(x, "axis"), "cell")
    expect_true(identical(attr(x, "daf"), d))
})

test_that("tbl() errors for missing axis", {
    skip_if_not_installed("dplyr")
    d <- memory_daf()
    expect_error(dplyr::tbl(d, "cell"), "axis")
})

test_that("collect() returns a tibble of the axis's vectors", {
    skip_if_not_installed("dplyr")
    skip_if_not_installed("tibble")
    d <- memory_daf()
    add_axis(d, "cell", c("c1", "c2", "c3"))
    set_vector(d, "cell", "donor", c("A", "B", "A"))
    set_vector(d, "cell", "age", c(10L, 20L, 30L))
    t <- dplyr::collect(dplyr::tbl(d, "cell"))
    expect_s3_class(t, "tbl_df")
    expect_setequal(colnames(t), c("name", "donor", "age"))
    expect_identical(t$name, c("c1", "c2", "c3"))
    expect_identical(t$donor, c("A", "B", "A"))
    expect_identical(t$age, c(10L, 20L, 30L))
})

test_that("as_tibble() is equivalent to collect() (modulo groups)", {
    skip_if_not_installed("dplyr")
    skip_if_not_installed("tibble")
    d <- memory_daf()
    add_axis(d, "cell", c("c1", "c2"))
    set_vector(d, "cell", "donor", c("A", "B"))
    t1 <- dplyr::collect(dplyr::tbl(d, "cell"))
    t2 <- tibble::as_tibble(dplyr::tbl(d, "cell"))
    expect_identical(t1, t2)
})

test_that("print() produces informative output without error", {
    skip_if_not_installed("dplyr")
    d <- memory_daf()
    add_axis(d, "cell", c("c1", "c2"))
    set_vector(d, "cell", "donor", c("A", "B"))
    out <- capture.output(print(dplyr::tbl(d, "cell")))
    expect_true(any(grepl("daf_axis_tbl", out)))
    expect_true(any(grepl("cell", out)))
})
