// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// altrep_mmap_r.cpp
SEXP mmap_real_altrep_cpp(std::string path, double length_double);
extern "C" SEXP _dafr_mmap_real_altrep_cpp(SEXP path, SEXP length_double) {
  BEGIN_CPP11
    return cpp11::as_sexp(mmap_real_altrep_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<double>>(length_double)));
  END_CPP11
}
// altrep_mmap_r.cpp
SEXP mmap_int_altrep_cpp(std::string path, double length_double);
extern "C" SEXP _dafr_mmap_int_altrep_cpp(SEXP path, SEXP length_double) {
  BEGIN_CPP11
    return cpp11::as_sexp(mmap_int_altrep_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<double>>(length_double)));
  END_CPP11
}
// altrep_mmap_r.cpp
SEXP mmap_lgl_altrep_cpp(std::string path, double length_double);
extern "C" SEXP _dafr_mmap_lgl_altrep_cpp(SEXP path, SEXP length_double) {
  BEGIN_CPP11
    return cpp11::as_sexp(mmap_lgl_altrep_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<double>>(length_double)));
  END_CPP11
}
// altrep_mmap_r.cpp
bool is_altrep_cpp(SEXP x);
extern "C" SEXP _dafr_is_altrep_cpp(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_altrep_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// kernel_eltwise_log_add.cpp
cpp11::writable::doubles kernel_log_add_cpp(cpp11::doubles x, cpp11::doubles y);
extern "C" SEXP _dafr_kernel_log_add_cpp(SEXP x, SEXP y) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_log_add_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_dafr_is_altrep_cpp",        (DL_FUNC) &_dafr_is_altrep_cpp,        1},
    {"_dafr_kernel_log_add_cpp",   (DL_FUNC) &_dafr_kernel_log_add_cpp,   2},
    {"_dafr_mmap_int_altrep_cpp",  (DL_FUNC) &_dafr_mmap_int_altrep_cpp,  2},
    {"_dafr_mmap_lgl_altrep_cpp",  (DL_FUNC) &_dafr_mmap_lgl_altrep_cpp,  2},
    {"_dafr_mmap_real_altrep_cpp", (DL_FUNC) &_dafr_mmap_real_altrep_cpp, 2},
    {NULL, NULL, 0}
};
}

void dafr_init_altrep_mmap(DllInfo* dll);

extern "C" attribute_visible void R_init_dafr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  dafr_init_altrep_mmap(dll);
  R_forceSymbols(dll, TRUE);
}
