// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// altrep_mmap_r.cpp
SEXP mmap_real_altrep_cpp(std::string path, double length_double);
extern "C" SEXP _dafr_mmap_real_altrep_cpp(SEXP path, SEXP length_double) {
  BEGIN_CPP11
    return cpp11::as_sexp(mmap_real_altrep_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<double>>(length_double)));
  END_CPP11
}
// altrep_mmap_r.cpp
SEXP mmap_int_altrep_cpp(std::string path, double length_double);
extern "C" SEXP _dafr_mmap_int_altrep_cpp(SEXP path, SEXP length_double) {
  BEGIN_CPP11
    return cpp11::as_sexp(mmap_int_altrep_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<double>>(length_double)));
  END_CPP11
}
// altrep_mmap_r.cpp
SEXP mmap_lgl_altrep_cpp(std::string path, double length_double);
extern "C" SEXP _dafr_mmap_lgl_altrep_cpp(SEXP path, SEXP length_double) {
  BEGIN_CPP11
    return cpp11::as_sexp(mmap_lgl_altrep_cpp(cpp11::as_cpp<cpp11::decay_t<std::string>>(path), cpp11::as_cpp<cpp11::decay_t<double>>(length_double)));
  END_CPP11
}
// altrep_mmap_r.cpp
bool is_altrep_cpp(SEXP x);
extern "C" SEXP _dafr_is_altrep_cpp(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(is_altrep_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// kernel_csc_colsums.cpp
cpp11::writable::doubles kernel_csc_colsums_cpp(cpp11::doubles x, cpp11::integers p, int ncol, int threshold);
extern "C" SEXP _dafr_kernel_csc_colsums_cpp(SEXP x, SEXP p, SEXP ncol, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_csc_colsums_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(ncol), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_eltwise_log_add.cpp
cpp11::writable::doubles kernel_log_add_cpp(cpp11::doubles x, cpp11::doubles y, int threshold);
extern "C" SEXP _dafr_kernel_log_add_cpp(SEXP x, SEXP y, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_log_add_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(y), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_geomean_csc.cpp
cpp11::writable::doubles kernel_geomean_csc_cpp(cpp11::doubles x, cpp11::integers i, cpp11::integers p, int nrow, int ncol, int axis, double eps, int threshold);
extern "C" SEXP _dafr_kernel_geomean_csc_cpp(SEXP x, SEXP i, SEXP p, SEXP nrow, SEXP ncol, SEXP axis, SEXP eps, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_geomean_csc_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<int>>(ncol), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<double>>(eps), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_grouped_minmax_dense.cpp
cpp11::writable::doubles_matrix<cpp11::by_column> kernel_grouped_minmax_dense_cpp(SEXP mat, cpp11::integers groups, int ngroups, int axis, int variant);
extern "C" SEXP _dafr_kernel_grouped_minmax_dense_cpp(SEXP mat, SEXP groups, SEXP ngroups, SEXP axis, SEXP variant) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_grouped_minmax_dense_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(mat), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(groups), cpp11::as_cpp<cpp11::decay_t<int>>(ngroups), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<int>>(variant)));
  END_CPP11
}
// kernel_grouped_mode_csc.cpp
cpp11::writable::doubles_matrix<cpp11::by_column> kernel_grouped_mode_csc_cpp(cpp11::doubles x, cpp11::integers i, cpp11::integers p, int nrow, int ncol, cpp11::integers group, int ngroups, cpp11::integers n_in_group, int axis, int threshold);
extern "C" SEXP _dafr_kernel_grouped_mode_csc_cpp(SEXP x, SEXP i, SEXP p, SEXP nrow, SEXP ncol, SEXP group, SEXP ngroups, SEXP n_in_group, SEXP axis, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_grouped_mode_csc_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<int>>(ncol), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(group), cpp11::as_cpp<cpp11::decay_t<int>>(ngroups), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(n_in_group), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_grouped_quantile_csc.cpp
cpp11::writable::doubles_matrix<cpp11::by_column> kernel_grouped_quantile_csc_cpp(cpp11::doubles x, cpp11::integers i, cpp11::integers p, int nrow, int ncol, cpp11::integers group, int ngroups, cpp11::integers n_in_group, int axis, double q, int threshold);
extern "C" SEXP _dafr_kernel_grouped_quantile_csc_cpp(SEXP x, SEXP i, SEXP p, SEXP nrow, SEXP ncol, SEXP group, SEXP ngroups, SEXP n_in_group, SEXP axis, SEXP q, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_grouped_quantile_csc_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<int>>(ncol), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(group), cpp11::as_cpp<cpp11::decay_t<int>>(ngroups), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(n_in_group), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<double>>(q), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_grouped_reduce_csc.cpp
cpp11::writable::doubles_matrix<cpp11::by_column> kernel_grouped_reduce_csc_cpp(cpp11::doubles x, cpp11::integers i, cpp11::integers p, int nrow, int ncol, cpp11::integers group, int ngroups, cpp11::integers n_in_group, int axis, std::string op, double eps, int threshold);
extern "C" SEXP _dafr_kernel_grouped_reduce_csc_cpp(SEXP x, SEXP i, SEXP p, SEXP nrow, SEXP ncol, SEXP group, SEXP ngroups, SEXP n_in_group, SEXP axis, SEXP op, SEXP eps, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_grouped_reduce_csc_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<int>>(ncol), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(group), cpp11::as_cpp<cpp11::decay_t<int>>(ngroups), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(n_in_group), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<std::string>>(op), cpp11::as_cpp<cpp11::decay_t<double>>(eps), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_grouped_reduce_dense.cpp
cpp11::writable::doubles_matrix<cpp11::by_column> kernel_grouped_reduce_dense_cpp(cpp11::doubles_matrix<> m, cpp11::integers group, int ngroups, cpp11::integers n_in_group, int axis, std::string op, double eps, int threshold);
extern "C" SEXP _dafr_kernel_grouped_reduce_dense_cpp(SEXP m, SEXP group, SEXP ngroups, SEXP n_in_group, SEXP axis, SEXP op, SEXP eps, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_grouped_reduce_dense_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(m), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(group), cpp11::as_cpp<cpp11::decay_t<int>>(ngroups), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(n_in_group), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<std::string>>(op), cpp11::as_cpp<cpp11::decay_t<double>>(eps), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_grouped_rowsum_dense.cpp
list kernel_grouped_rowsum_dense_cpp(SEXP mat, cpp11::integers groups, int ngroups, bool need_sq, int axis);
extern "C" SEXP _dafr_kernel_grouped_rowsum_dense_cpp(SEXP mat, SEXP groups, SEXP ngroups, SEXP need_sq, SEXP axis) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_grouped_rowsum_dense_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(mat), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(groups), cpp11::as_cpp<cpp11::decay_t<int>>(ngroups), cpp11::as_cpp<cpp11::decay_t<bool>>(need_sq), cpp11::as_cpp<cpp11::decay_t<int>>(axis)));
  END_CPP11
}
// kernel_log_reduce.cpp
cpp11::writable::doubles kernel_log_reduce_dense_cpp(cpp11::doubles_matrix<> m, double eps, double base, int axis, std::string reducer, int threshold);
extern "C" SEXP _dafr_kernel_log_reduce_dense_cpp(SEXP m, SEXP eps, SEXP base, SEXP axis, SEXP reducer, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_log_reduce_dense_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles_matrix<>>>(m), cpp11::as_cpp<cpp11::decay_t<double>>(eps), cpp11::as_cpp<cpp11::decay_t<double>>(base), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<std::string>>(reducer), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_log_reduce.cpp
cpp11::writable::doubles kernel_log_reduce_csc_cpp(cpp11::doubles x, cpp11::integers i, cpp11::integers p, int nrow, int ncol, double eps, double base, int axis, std::string reducer, int threshold);
extern "C" SEXP _dafr_kernel_log_reduce_csc_cpp(SEXP x, SEXP i, SEXP p, SEXP nrow, SEXP ncol, SEXP eps, SEXP base, SEXP axis, SEXP reducer, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_log_reduce_csc_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<int>>(ncol), cpp11::as_cpp<cpp11::decay_t<double>>(eps), cpp11::as_cpp<cpp11::decay_t<double>>(base), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<std::string>>(reducer), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_minmax_csc.cpp
cpp11::writable::doubles kernel_minmax_csc_cpp(cpp11::doubles x, cpp11::integers i, cpp11::integers p, int nrow, int ncol, int axis, std::string variant, int threshold);
extern "C" SEXP _dafr_kernel_minmax_csc_cpp(SEXP x, SEXP i, SEXP p, SEXP nrow, SEXP ncol, SEXP axis, SEXP variant, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_minmax_csc_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<int>>(ncol), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<std::string>>(variant), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_mode_csc.cpp
cpp11::writable::doubles kernel_mode_csc_cpp(cpp11::doubles x, cpp11::integers i, cpp11::integers p, int nrow, int ncol, int axis, int threshold);
extern "C" SEXP _dafr_kernel_mode_csc_cpp(SEXP x, SEXP i, SEXP p, SEXP nrow, SEXP ncol, SEXP axis, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_mode_csc_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<int>>(ncol), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_mode_dense.cpp
cpp11::writable::doubles kernel_mode_dense_cpp(SEXP mat, int axis, int threshold);
extern "C" SEXP _dafr_kernel_mode_dense_cpp(SEXP mat, SEXP axis, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_mode_dense_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(mat), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_quantile_csc.cpp
cpp11::writable::doubles kernel_quantile_csc_cpp(cpp11::doubles x, cpp11::integers i, cpp11::integers p, int nrow, int ncol, int axis, double q, int threshold);
extern "C" SEXP _dafr_kernel_quantile_csc_cpp(SEXP x, SEXP i, SEXP p, SEXP nrow, SEXP ncol, SEXP axis, SEXP q, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_quantile_csc_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<int>>(ncol), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<double>>(q), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_quantile_dense.cpp
cpp11::writable::doubles kernel_quantile_dense_cpp(SEXP mat, int axis, double q, int threshold);
extern "C" SEXP _dafr_kernel_quantile_dense_cpp(SEXP mat, SEXP axis, SEXP q, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_quantile_dense_cpp(cpp11::as_cpp<cpp11::decay_t<SEXP>>(mat), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<double>>(q), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}
// kernel_var_csc.cpp
cpp11::writable::doubles kernel_var_csc_cpp(cpp11::doubles x, cpp11::integers i, cpp11::integers p, int nrow, int ncol, int axis, std::string variant, double eps, int threshold);
extern "C" SEXP _dafr_kernel_var_csc_cpp(SEXP x, SEXP i, SEXP p, SEXP nrow, SEXP ncol, SEXP axis, SEXP variant, SEXP eps, SEXP threshold) {
  BEGIN_CPP11
    return cpp11::as_sexp(kernel_var_csc_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(p), cpp11::as_cpp<cpp11::decay_t<int>>(nrow), cpp11::as_cpp<cpp11::decay_t<int>>(ncol), cpp11::as_cpp<cpp11::decay_t<int>>(axis), cpp11::as_cpp<cpp11::decay_t<std::string>>(variant), cpp11::as_cpp<cpp11::decay_t<double>>(eps), cpp11::as_cpp<cpp11::decay_t<int>>(threshold)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_dafr_is_altrep_cpp",                   (DL_FUNC) &_dafr_is_altrep_cpp,                    1},
    {"_dafr_kernel_csc_colsums_cpp",          (DL_FUNC) &_dafr_kernel_csc_colsums_cpp,           4},
    {"_dafr_kernel_geomean_csc_cpp",          (DL_FUNC) &_dafr_kernel_geomean_csc_cpp,           8},
    {"_dafr_kernel_grouped_minmax_dense_cpp", (DL_FUNC) &_dafr_kernel_grouped_minmax_dense_cpp,  5},
    {"_dafr_kernel_grouped_mode_csc_cpp",     (DL_FUNC) &_dafr_kernel_grouped_mode_csc_cpp,     10},
    {"_dafr_kernel_grouped_quantile_csc_cpp", (DL_FUNC) &_dafr_kernel_grouped_quantile_csc_cpp, 11},
    {"_dafr_kernel_grouped_reduce_csc_cpp",   (DL_FUNC) &_dafr_kernel_grouped_reduce_csc_cpp,   12},
    {"_dafr_kernel_grouped_reduce_dense_cpp", (DL_FUNC) &_dafr_kernel_grouped_reduce_dense_cpp,  8},
    {"_dafr_kernel_grouped_rowsum_dense_cpp", (DL_FUNC) &_dafr_kernel_grouped_rowsum_dense_cpp,  5},
    {"_dafr_kernel_log_add_cpp",              (DL_FUNC) &_dafr_kernel_log_add_cpp,               3},
    {"_dafr_kernel_log_reduce_csc_cpp",       (DL_FUNC) &_dafr_kernel_log_reduce_csc_cpp,       10},
    {"_dafr_kernel_log_reduce_dense_cpp",     (DL_FUNC) &_dafr_kernel_log_reduce_dense_cpp,      6},
    {"_dafr_kernel_minmax_csc_cpp",           (DL_FUNC) &_dafr_kernel_minmax_csc_cpp,            8},
    {"_dafr_kernel_mode_csc_cpp",             (DL_FUNC) &_dafr_kernel_mode_csc_cpp,              7},
    {"_dafr_kernel_mode_dense_cpp",           (DL_FUNC) &_dafr_kernel_mode_dense_cpp,            3},
    {"_dafr_kernel_quantile_csc_cpp",         (DL_FUNC) &_dafr_kernel_quantile_csc_cpp,          8},
    {"_dafr_kernel_quantile_dense_cpp",       (DL_FUNC) &_dafr_kernel_quantile_dense_cpp,        4},
    {"_dafr_kernel_var_csc_cpp",              (DL_FUNC) &_dafr_kernel_var_csc_cpp,               9},
    {"_dafr_mmap_int_altrep_cpp",             (DL_FUNC) &_dafr_mmap_int_altrep_cpp,              2},
    {"_dafr_mmap_lgl_altrep_cpp",             (DL_FUNC) &_dafr_mmap_lgl_altrep_cpp,              2},
    {"_dafr_mmap_real_altrep_cpp",            (DL_FUNC) &_dafr_mmap_real_altrep_cpp,             2},
    {NULL, NULL, 0}
};
}

void dafr_init_altrep_mmap(DllInfo* dll);

extern "C" attribute_visible void R_init_dafr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  dafr_init_altrep_mmap(dll);
  R_forceSymbols(dll, TRUE);
}
