# Generated by cpp11: do not edit by hand

mmap_real_altrep_cpp <- function(path, length_double) {
  .Call(`_dafr_mmap_real_altrep_cpp`, path, length_double)
}

mmap_int_altrep_cpp <- function(path, length_double) {
  .Call(`_dafr_mmap_int_altrep_cpp`, path, length_double)
}

mmap_lgl_altrep_cpp <- function(path, length_double) {
  .Call(`_dafr_mmap_lgl_altrep_cpp`, path, length_double)
}

is_altrep_cpp <- function(x) {
  .Call(`_dafr_is_altrep_cpp`, x)
}

kernel_csc_colsums_cpp <- function(x, p, ncol, threshold) {
  .Call(`_dafr_kernel_csc_colsums_cpp`, x, p, ncol, threshold)
}

kernel_csc_to_csr_cpp <- function(x, i, p, nrow, ncol) {
  .Call(`_dafr_kernel_csc_to_csr_cpp`, x, i, p, nrow, ncol)
}

kernel_log_add_cpp <- function(x, y, threshold) {
  .Call(`_dafr_kernel_log_add_cpp`, x, y, threshold)
}

kernel_log_reduce_dense_cpp <- function(m, eps, base, axis, reducer, threshold) {
  .Call(`_dafr_kernel_log_reduce_dense_cpp`, m, eps, base, axis, reducer, threshold)
}

kernel_log_reduce_csc_cpp <- function(x, i, p, nrow, ncol, eps, base, axis, reducer, threshold) {
  .Call(`_dafr_kernel_log_reduce_csc_cpp`, x, i, p, nrow, ncol, eps, base, axis, reducer, threshold)
}

kernel_minmax_csc_cpp <- function(x, i, p, nrow, ncol, axis, variant, threshold) {
  .Call(`_dafr_kernel_minmax_csc_cpp`, x, i, p, nrow, ncol, axis, variant, threshold)
}

kernel_var_csc_cpp <- function(x, i, p, nrow, ncol, axis, variant, eps, threshold) {
  .Call(`_dafr_kernel_var_csc_cpp`, x, i, p, nrow, ncol, axis, variant, eps, threshold)
}
