# Generated by cpp11: do not edit by hand

mmap_real_altrep_cpp <- function(path, length_double) {
  .Call(`_dafr_mmap_real_altrep_cpp`, path, length_double)
}

mmap_int_altrep_cpp <- function(path, length_double) {
  .Call(`_dafr_mmap_int_altrep_cpp`, path, length_double)
}

mmap_lgl_altrep_cpp <- function(path, length_double) {
  .Call(`_dafr_mmap_lgl_altrep_cpp`, path, length_double)
}

is_altrep_cpp <- function(x) {
  .Call(`_dafr_is_altrep_cpp`, x)
}

kernel_csc_colsums_cpp <- function(x, p, ncol, threshold) {
  .Call(`_dafr_kernel_csc_colsums_cpp`, x, p, ncol, threshold)
}

kernel_log_add_cpp <- function(x, y, threshold) {
  .Call(`_dafr_kernel_log_add_cpp`, x, y, threshold)
}

kernel_geomean_csc_cpp <- function(x, i, p, nrow, ncol, axis, eps, threshold) {
  .Call(`_dafr_kernel_geomean_csc_cpp`, x, i, p, nrow, ncol, axis, eps, threshold)
}

kernel_grouped_minmax_dense_cpp <- function(mat, groups, ngroups, axis, variant, threshold) {
  .Call(`_dafr_kernel_grouped_minmax_dense_cpp`, mat, groups, ngroups, axis, variant, threshold)
}

kernel_grouped_mode_csc_cpp <- function(x, i, p, nrow, ncol, group, ngroups, n_in_group, axis, threshold) {
  .Call(`_dafr_kernel_grouped_mode_csc_cpp`, x, i, p, nrow, ncol, group, ngroups, n_in_group, axis, threshold)
}

kernel_grouped_quantile_csc_cpp <- function(x, i, p, nrow, ncol, group, ngroups, n_in_group, axis, q, threshold) {
  .Call(`_dafr_kernel_grouped_quantile_csc_cpp`, x, i, p, nrow, ncol, group, ngroups, n_in_group, axis, q, threshold)
}

kernel_grouped_reduce_csc_cpp <- function(x, i, p, nrow, ncol, group, ngroups, n_in_group, axis, op, eps, threshold) {
  .Call(`_dafr_kernel_grouped_reduce_csc_cpp`, x, i, p, nrow, ncol, group, ngroups, n_in_group, axis, op, eps, threshold)
}

kernel_grouped_reduce_dense_cpp <- function(m, group, ngroups, n_in_group, axis, op, eps, threshold) {
  .Call(`_dafr_kernel_grouped_reduce_dense_cpp`, m, group, ngroups, n_in_group, axis, op, eps, threshold)
}

kernel_grouped_rowsum_dense_cpp <- function(mat, groups, ngroups, need_sq, axis, threshold) {
  .Call(`_dafr_kernel_grouped_rowsum_dense_cpp`, mat, groups, ngroups, need_sq, axis, threshold)
}

kernel_log_reduce_dense_cpp <- function(m, eps, base, axis, reducer, threshold) {
  .Call(`_dafr_kernel_log_reduce_dense_cpp`, m, eps, base, axis, reducer, threshold)
}

kernel_log_reduce_csc_cpp <- function(x, i, p, nrow, ncol, eps, base, axis, reducer, threshold) {
  .Call(`_dafr_kernel_log_reduce_csc_cpp`, x, i, p, nrow, ncol, eps, base, axis, reducer, threshold)
}

kernel_minmax_csc_cpp <- function(x, i, p, nrow, ncol, axis, variant, threshold) {
  .Call(`_dafr_kernel_minmax_csc_cpp`, x, i, p, nrow, ncol, axis, variant, threshold)
}

kernel_mode_csc_cpp <- function(x, i, p, nrow, ncol, axis, threshold) {
  .Call(`_dafr_kernel_mode_csc_cpp`, x, i, p, nrow, ncol, axis, threshold)
}

kernel_mode_dense_cpp <- function(mat, axis, threshold) {
  .Call(`_dafr_kernel_mode_dense_cpp`, mat, axis, threshold)
}

kernel_quantile_csc_cpp <- function(x, i, p, nrow, ncol, axis, q, threshold) {
  .Call(`_dafr_kernel_quantile_csc_cpp`, x, i, p, nrow, ncol, axis, q, threshold)
}

kernel_quantile_dense_cpp <- function(mat, axis, q, threshold) {
  .Call(`_dafr_kernel_quantile_dense_cpp`, mat, axis, q, threshold)
}

kernel_var_csc_cpp <- function(x, i, p, nrow, ncol, axis, variant, eps, threshold) {
  .Call(`_dafr_kernel_var_csc_cpp`, x, i, p, nrow, ncol, axis, variant, eps, threshold)
}

dafr_set_num_threads <- function(n) {
  invisible(.Call(`_dafr_dafr_set_num_threads`, n))
}

dafr_get_max_threads <- function() {
  .Call(`_dafr_dafr_get_max_threads`)
}
